import { Column } from "../interfaces/table";
import { Vehicle } from "../interfaces/vehicles";

export const vehicleColumns: Column[] = [
  { key: "brand", label: "Brand", size: 100, alignment: "center" },
  { key: "model", label: "Model", size: 100, alignment: "center" },
  { key: "year", label: "Year", size: 100, alignment: "center" },
  { key: "fuelType", label: "Fuel type", size: 100, alignment: "center" },
  { key: "kilometers", label: "Kilometers", size: 100, alignment: "center" },
];

export const vehicleRows: Vehicle[] = [
  {
    id: 1,
    brand: "Nissan",
    model: "Micra",
    year: 2019,
    fuelType: "Gasoline",
    kilometers: "1780",
  },
  {
    id: 2,
    brand: "Mazda",
    model: "3",
    year: 2014,
    fuelType: "Gasoline",
    kilometers: "109000",
  },
  {
    id: 3,
    brand: "Ford",
    model: "Fiesta",
    year: 2020,
    fuelType: "Diesel",
    kilometers: "28000",
  },
  {
    id: 4,
    brand: "Honda",
    model: "Civic",
    year: 1996,
    fuelType: "Gasoline",
    kilometers: "123900",
  },
  {
    id: 5,
    brand: "Subaru",
    model: "Impreza",
    year: 2004,
    fuelType: "Diesel",
    kilometers: "320120",
  },
  {
    id: 6,
    brand: "Toyota",
    model: "Hilux",
    year: 2001,
    fuelType: "Diesel",
    kilometers: "999999",
  },
  {
    id: 7,
    brand: "Toyota",
    model: "Corolla",
    year: 2021,
    fuelType: "Hybrid",
    kilometers: "3200",
  },
  {
    id: 8,
    brand: "Ford",
    model: "Mustang",
    year: 2020,
    fuelType: "Gasoline",
    kilometers: "15000",
  },
  {
    id: 9,
    brand: "Tesla",
    model: "Model 3",
    year: 2022,
    fuelType: "Electric",
    kilometers: "500",
  },
  {
    id: 10,
    brand: "BMW",
    model: "X5",
    year: 2018,
    fuelType: "Diesel",
    kilometers: "25000",
  },
  {
    id: 11,
    brand: "Audi",
    model: "A4",
    year: 2017,
    fuelType: "Gasoline",
    kilometers: "30000",
  },
  {
    id: 12,
    brand: "Honda",
    model: "Civic",
    year: 2019,
    fuelType: "Gasoline",
    kilometers: "12000",
  },
  {
    id: 13,
    brand: "Chevrolet",
    model: "Spark",
    year: 2020,
    fuelType: "Gasoline",
    kilometers: "5000",
  },
  {
    id: 14,
    brand: "Volkswagen",
    model: "Golf",
    year: 2018,
    fuelType: "Diesel",
    kilometers: "22000",
  },
  {
    id: 15,
    brand: "Hyundai",
    model: "Elantra",
    year: 2021,
    fuelType: "Gasoline",
    kilometers: "10000",
  },
];
